name: "benchmarks"
on:
  push:
  pull_request:
    branches: 
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: "install golang"
        uses: jake-young-dev/install-go@v1.0.0
        with:
          - purge: yes

      - name: bench
        shell: bash
        run: ./scripts/bench.sh
