name: Tests

on:
  push:
    branches: [ "**" ]
    paths:
      - "*.go"
      - "*.yaml"
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: jake-young-dev/go-install-script@v0.2.1

      - name: test
        shell: bash
        run: go test -v -cover
  extra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: test
        shell: bash
        run: go test -v -cover
