name: "security scan"
on:
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: "install golang"
        uses: jake-young-dev/install-go@v1.0.0
        with:
          - purge: yes
      
      - name: security scan
        uses: securego/gosec@v2.22.3
        with:
          args: ./...