name: tests

on:
  push:
    branches: [ "**" ]
    paths:
      - "*.go"
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: jake-young-dev/go-install-script@v0.3.0
        with:
          architecture: amd64
          purge: yes

      - name: test
        shell: bash
        run: go test -cover
