name: tests
on:
  push:
    branches: [ "**" ]
    paths:
      - "*.go"
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: unit tests
        shell: bash
        run: go test -cover
