name: tests

on:
  push:
    branches: [ "**" ]
    paths:
      - "*.go"
      - ".github/workflows/test.yaml"
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: https://code.jakeyoungdev.com/actions/install-go@v0.1.3
        with:
          purge: yes

      - name: unit tests
        shell: bash
        run: go test -cover
